language: java
branches:
  only:
  - master
  - develop
  - "/^v.*$/"
before_deploy:
- "./gradlew build"
deploy:
  provider: releases
  api_key:
    secure: H0f9l7MDjjn2pbwsyrJbeFL8SSn4daYb9hz/+gdoFwTo8C7btC2b9tiQH6wH3R+V51pTDC75XXFQUg7F1Tjd973yLPDZXASTm9j3LF0l79MsJJDnvL8oOoj8h+VOqN8hpkc87jUTNmYfKqwNzXt2+Iy+kqzABGoU+njZ13KWuq9XLVmEZPGqXrU6Xj1UG5tdt6j0UO7IdwUY7ux585huO23SwjUPE45sVh8SYT9K7bW0NGT7o0GecMZL+WGwld9wNIuQ/bDMNbGYzq1a+aT0EXDZRtHTlicUxslHBzFoRvq8VRPAEs7X81mSwy2ghYUzvtj/w0UCM9DzKWbTaATFluf9aGxemvTWhRk5qTh0PoZ4HICg31nSTEjzhDR/Us6XaysuDfC//2o+HLKz68pjfVM3zJZh8RN8Th9oISNPEnAukEFCRvuUN0QPw1Bui6fiKuI+vNczXcC4JAlSvj9c8z/dh+I3gZ+gHVXMpU0WjT3wWwU72l5nFBgz37TuUxWEQYMEMftu4ikGX+i8MsrUM0KKGj2XIBIWSWyqGx+zUZ3BsyTixALD0e9DRcx2U1+rD3b8pl3f5OdVd1Ln/0tzanX2Gpk8/exUBTstJMqDMCkgsju1FjAId15HDYtsgHwsPxvEClCNaoidbd+HxGZ+Z18X9YbdX4yb2dHqb0zRogU=
  file: dist/owl2neo4j.jar
  skip_cleanup: true
  on:
    repo: flekschas/owl2neo4j
    tags: true
